### PR TITLE
ENH: Providing ITKv5 updates for C++11

### PR DESCRIPTION
**Pull request by hjmjohnson**
This pull request incorporates code changes
that happened in parallel with updating the
core ITK code to ITKv5 for C++11 conformity.

### CODE REVIEW

**Comment by jhlegarreta** [comment]
The **errors** in the `ci/circle: package` seem to have to do with the C compiler used (by the image) not being able to use C++11 (?); or  may be Python 2.7 requiring a C compiler that is not able to use C++11?

The **travis build** reports a **CMake minimum required error**:
```
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.9.5 or higher is required.  You are running version 3.9.4
```

So I guess that has to do with the CMake shipped by the container.

**Comment by jhlegarreta** [comment]
CircleCI's error may have to do with the compiler used.

TravisCI reports a CMake minimum version error.

**Comment by hjmjohnson** [comment]
@jhlegarreta I don't have the time to track down circleci issues.  Is this something that you are familiar with?

**Comment by jhlegarreta** [comment]
@hjmjohnson Not really; I'm opening an issue so that this can be tracked and done when we have more time.

**Pull request merged**
