### PR TITLE
BUG: Fix failing example

### PR DESCRIPTION
**Pull request by mseng10**
I have included a Data subdirectory in `AnisotropicDiffusionLBR/examples/Data` and uploaded the raw png file: PacMan.png. This is used for the example's test, and any user who may wish to experiment with the module.

In addition, the image was not being properly read, so I required the ITKIOImageBase module be imported for proper reading.

Lastly, a minor spelling error was fixed.

This PR is a WIP, I will update it based on these test results.

### CODE REVIEW

**Comment by mseng10** [comment]
@hjmjohnson It seems the only errors being thrown are related to the KWStyle checking which should be handled in the ITKv5_1rc2 merge. Should I rebase the changes on top of that branch, or keep this as a WIP until it is merged?

**Comment by hjmjohnson** [comment]
@mseng10. rebase on top of master,  ensure that a clean build occurs with the master of ITK, and the master of all remote modules.

**Comment by mseng10** [comment]
@hjmjohnson Several of the jobs are stuck in the queue despite no job presently running.

**Comment by mseng10** [comment]
Recent changes remove the old ci testing to fit the new ITKModuleTemplate. New ci testing will be implemented in #40. Also, I changed the azure-pipeline `ITKGitTag` and `ITKPythonGitTag` to v5.1rc03.

**Comment by thewtex** [comment]
@mseng10 please try re-basing on `master`.

**Comment by mseng10** [comment]
> @mseng10 please try re-basing on `master`.

@thewtex Just rebased and pushed, should be good to go.

**Comment by thewtex** [comment]
Appveyor, TravisCI, and CircleCI services have been disabled.

**Pull request merged**
