### PR TITLE
BUG: Download packages for PyPI upload on Linux

### PR DESCRIPTION
**Pull request by thewtex**
The PyPI upload action cannot be executed on Windows.

### CODE REVIEW

**Comment by hjmjohnson** [comment]
@thewtex Thank you for working on this.

**Comment by thewtex** [comment]
@hjmjohnson this will really be wonderful. I am going to test here and a few other modules, but it would be awesome to have your help spreading the development joy to the rest of the remote modules.

**Comment by hjmjohnson** [comment]
@thewtex I will work with @mseng10 to coordinate bringing the remote modules up-to-date.

Could you provide a 2-minute cheat sheet for what you view as needing to be done?

## For each remote module:
 - [ ] Disable Travis
 - [ ] Disable CircleCI
 - [ ] Enable Githbub actions
 - [ ] cp `.github/workflows/build-test-package.yml ` from template to each module & make PR
 - [ ] Monitor builds and addresses issues that arise (either make issues or fix warnings/test failures/ etc).
 - [ ] Update ${MODULE}.remote.cmake to reflect `Grading Level Criteria Report`

**Comment by thewtex** [comment]
@hjmjohnson awesome, thank you so much! :sparkling_heart: 

I updated your list -- please let me know if anything is unclear. @dzenanz and I can help disable the Azure Pipelines hooks.

One of the awesome improvements with GitHub Actions is that it does not require an extra account, administration of privileges, etc. -- one the configuration file is added to the repository, it is automatically utilized.

**Pull request merged**
