### PR TITLE
GitHub Actions

### PR DESCRIPTION
**Pull request by thewtex**

### CODE REVIEW

**Comment by thewtex** [comment]
@hjmjohnson @mseng10 feel free to run with this.

Todos:

- [ ] Address any new warnings
- [ ] Add Windows build to the matrix
- [ ] Add macOS build to the matrix

The Windows and macOS configuration should be similar to Azure Pipelines.

**Comment by thewtex** [comment]
Failing Linux packaging issue is related to disk space issues: https://github.community/t5/GitHub-Actions/Failure-with-missing-logs/m-p/55055/highlight/false#M9401

**Comment by thewtex** [comment]
> disk space issues

In 5.1.0 we will remove the ITKPythonBuild tarball after it has been extracted to save disk space.

**Comment by mseng10** [comment]
@thewtex Just to clarify this would be `ITKPythonBuilds-linux.tar.zst`?

**Comment by thewtex** [comment]
@mseng10 `ITKPythonBuilds-linux.tar`, which is ~5GB.

**Comment by hjmjohnson** [comment]
@thewtex Thank you for working on this.  @mseng10 will follow your lead and implement this on other remote modules once it is working well.

**Comment by thewtex** [comment]
> @thewtex Thank you for working on this. @mseng10 will follow your lead and implement this on other remote modules once it is working well.

Awesome, thank you! That will be very helpful. CI for remote modules will not only working again after this is resolved, but it will be elegant and joyful to use :sparkling_heart: .

**Pull request merged**
